#!/bin/bash

# SBATCH --nodes=1
# SBATCH --partition  RM-shared # partition name
# SBATCH --ntasks-per-node=128
# SBATCH -t 5:00:00 # hours:minutes runlimit after which job will be killed
# SBATCH -c 12 # number of cores requested -- this needs to be greater than or equal to the number of cores you plan to use to run your job
# SBATCH --mem 12G 
# SBATCH --job-name star_genome_generate # Job name
# SBATCH -o %j.out # File to which standard out will be written
# SBATCH -e %j.err # File to which standard err will be written

group_num="group$1"
LINES=$(tail -n +2 $PROJECT/../shared/$group_num/data/sample-links.txt | cut -d '|' -f 1-5)
declare -a file_array=()
for LINE in $LINES
do
    touch interim.txt
    echo $LINE>>interim.txt
    file=$(cut -f1 -d "|" interim.txt)
    file_array+="$file "
    rm interim.txt
done
echo $file_array

module load STAR/2.7.6a cutadapt/2.10 
set -x

for FILE in $file_array
do 
    cd $PROJECT/../shared/$group_num/data/K562/$FILE 

        echo "CUTADAPT 1 ..."
        cutadapt -f fastq --match-read-wildcards --times 1 -e 0.1 -O 1 --quality-cutoff 6 -m 18 -a NNNNNAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -g CTTCCGATCTACAAGTT -g CTTCCGATCTTGGTCCT -A AACTTGTAGATCGGA -A AGGACCAAGATCGGA -A ACTTGTAGATCGGAA -A GGACCAAGATCGGAA -A CTTGTAGATCGGAAG -A GACCAAGATCGGAAG -A TTGTAGATCGGAAGA -A ACCAAGATCGGAAGA -A TGTAGATCGGAAGAG -A CCAAGATCGGAAGAG -A GTAGATCGGAAGAGC -A CAAGATCGGAAGAGC -A TAGATCGGAAGAGCG -A AAGATCGGAAGAGCG -A AGATCGGAAGAGCGT -A GATCGGAAGAGCGTC -A ATCGGAAGAGCGTCG -A TCGGAAGAGCGTCGT -A CGGAAGAGCGTCGTG -A GGAAGAGCGTCGTGT -o $FILE.r1.cutadapt1.fq -p $FILE.r2.cutadapt1.fq read1.fastq read2.fastq

        echo "CUTADAPT 2 ..."
        cutadapt -f fastq --match-read-wildcards --times 1 -e 0.1 -O 5 --quality-cutoff 6 -m 18 -A AACTTGTAGATCGGA -A AGGACCAAGATCGGA -A ACTTGTAGATCGGAA -A GGACCAAGATCGGAA -A CTTGTAGATCGGAAG -A GACCAAGATCGGAAG -A TTGTAGATCGGAAGA -A ACCAAGATCGGAAGA -A TGTAGATCGGAAGAG -A CCAAGATCGGAAGAG -A GTAGATCGGAAGAGC -A CAAGATCGGAAGAGC -A TAGATCGGAAGAGCG -A AAGATCGGAAGAGCG -A AGATCGGAAGAGCGT -A GATCGGAAGAGCGTC -A ATCGGAAGAGCGTCG -A TCGGAAGAGCGTCGT -A CGGAAGAGCGTCGTG -A GGAAGAGCGTCGTGT -o $FILE.r1.cutadapt2.fq -p $FILE.r2.cutadapt2.fq $FILE.r1.cutadapt1.fq $FILE.r2.cutadapt1.fq

        echo "FASTQ SORTING ..."
        fastq-sort --id $FILE.r1.cutadapt2.fq > $FILE.r1.cutadapt2.fastq.sorted.fq
        fastq-sort --id $FILE.r2.cutadapt2.fq > $FILE.r2.cutadapt2.fastq.sorted.fq

        echo "STAR GENOME INDEXING ..."
        STAR --runThreadN 12 --runMode genomeGenerate --genomeDir ../../GenomeDir --genomeFastaFiles ../../ref-seq-ucsc/hg38.fa --sjdbGTFtagExonParentTranscript ../../ref-seq-ucsc/hg38.refGene.gtf

        echo "STAR ALIGN 1 ..."
        STAR --runMode alignReads --runThreadN 12 --genomeDir ../../GenomeDir --genomeLoad NoSharedMemory --alignEndsType EndToEnd --outSAMunmapped Within --outFilterMultimapNmax 30 --outFilterMultimapScoreRange 1 --outFileNamePrefix $FILE.rep2_clip.C01.r1.fqTrTr.sorted.STAR --outSAMtype BAM Unsorted --outFilterType BySJout --outBAMcompression 10 --outReadsUnmapped Fastx --outFilterScoreMin 10 --outSAMattrRGline ID:foo --outSAMattributes All --outSAMmode Full --outStd Log --readFilesIn $PROJECT/../shared/$group_num/data/K562/$FILE/$FILE.r1.cutadapt2.fastq.sorted.fq $PROJECT/../shared/$group_num/data/K562/$FILE/$FILE.r2.cutadapt2.fastq.sorted.fq

        echo "RENAMING FILES ..."
        mv ./$FILE.rep2_clip.C01.r1.fqTrTr.sorted.STARAligned.out.bam $FILE.rep2_clip.C01.r1.fq.repeat-mapped.bam
        mv ./$FILE.rep2_clip.C01.r1.fqTrTr.sorted.STARUnmapped.out.mate1 $FILE.rep2_clip.C01.r1.fq.repeat-unmapped.fq 
        mv ./$FILE.rep2_clip.C01.r1.fqTrTr.sorted.STARUnmapped.out.mate2 $FILE.rep2_clip.C01.r2.fq.repeat-unmapped.fq

        echo "Performing FASTQ SORT ..."
        fastq-sort --id $FILE.rep2_clip.C01.r1.fq.repeat-unmapped.fq > $FILE.rep2_clip.C01.r1.fq.repeat-unmapped.sorted.fq
        fastq-sort --id $FILE.rep2_clip.C01.r2.fq.repeat-unmapped.fq > $FILE.rep2_clip.C01.r2.fq.repeat-unmapped.sorted.fq

        echo "STAR ALIGN 2 ..."
        STAR --runMode alignReads --runThreadN 12 --genomeDir ../../GenomeDir --genomeLoad NoSharedMemory --readFilesIn $PROJECT/../shared/$group_num/data/K562/$FILE/$FILE.rep2_clip.C01.r1.fq.repeat-unmapped.sorted.fq $PROJECT/../shared/$group_num/data/K562/$FILE/$FILE.rep2_clip.C01.r2.fq.repeat-unmapped.sorted.fq --outSAMunmapped Within --outFilterMultimapNmax 1 --outFilterMultimapScoreRange 1 --outFileNamePrefix $FILE.rep2_clip.C01.r1.fq.repeat-unmapped.sorted.STAR --outSAMattributes All --outSAMtype BAM Unsorted --outFilterType BySJout --outReadsUnmapped Fastx --outFilterScoreMin 10 --outSAMattrRGline ID:foo --outStd Log --alignEndsType EndToEnd --outBAMcompression 10 --outSAMmode Full

        echo "RENAMING BAM FILES ..."
        mv $FILE.rep2_clip.C01.r1.fq.repeat-unmapped.sorted.STARAligned.out.bam $FILE.rep2_clip.C01.r1.fq.genome-mapped.bam

        echo "SAMTOOLS SORTING ..."
        samtools sort -n -o $FILE.rep2_clip.C01.r1.fq.genome-mappedSo.bam $FILE.rep2_clip.C01.r1.fq.genome-mapped.bam

        cd ../
done
echo "PREPROCESS 1 COMPLETE!"
